# docker-compose file to test the dockerization of parma-analytics (not the database)
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./parma_analytics:/app/parma_analytics
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
