name: parma-analytics
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Git
  - pre-commit
  # Python
  - pip
  - python =3.11
  - setuptools-scm
  - setuptools >=61 # pyproject.toml support
  # Infrastructure provisioning (IAC)
  - terraform=1.5.3
  - tflint=0.47.0
  - yamllint=1.32.0
  # Development
  - types-pyyaml
  - google-cloud-sdk
  - ipykernel
  # Testing
  - pytest >=6 # --import-mode option
  - pytest-cov
  # Dependencies (core)
  - fastapi >=0.104.0
  - httpx
  - polars >=0.19.0
  - pydantic >=2
  - pyyaml
  - typer >=0.9.0
  - uvicorn[standard]
  - requests
  - sendgrid
  - python-dotenv
  - slack_sdk
  - pip:
      - firebase-admin ==6.2.0
      - google-cloud-secret-manager
      - xhtml2pdf ==0.2.13
  - matplotlib >=3.8.2
  - matplotlib-inline >=0.1.6
  - Jinja2 >=3.1.2
  - reportlab =4.0.8
  # Dependencies (db)
  - sqlalchemy >=2.0
  - psycopg2 >=2.9
