# reduced environment for production (no dev dependencies to keep docker image small)
name: parma-analytics
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Python
  - pip
  - python =3.11
  - setuptools-scm
  - setuptools >=61 # pyproject.toml support
  - pytest-cov
  # Dependencies (core)
  - fastapi >=0.104.0
  - httpx
  - polars >=0.19.0
  - pydantic >=2
  - pyyaml
  - typer >=0.9.0
  - uvicorn[standard]
  - requests
  - sendgrid
  - python-dotenv
  - slack_sdk
  - pip:
      - firebase-admin==6.2.0
      - xhtml2pdf ==0.2.13
  - matplotlib >=3.8.2
  - matplotlib-inline >=0.1.6
  - Jinja2 >=3.1.2
  - reportlab =4.0.8
  # Dependencies (db)
  - sqlalchemy >=2.0
  - psycopg2 >=2.9
  - pip:
      - firebase-admin==6.2.0
